### PR TITLE
Fix #28 and #38 by using babel-preset-es2015

### LINKED ISSUE #28: Issue with UglifyJS while packing production build
Hello,

I have no problem using transliterate in my dev environment, however, when I try to generate my production build I get an error with webpack 2 UglifyJS plugin complaining about `codemap`:

```
ERROR in /app-1b68d4b985561a4f9537.js from UglifyJs
SyntaxError: Unexpected token: name (codemap) [/app-1b68d4b985561a4f9537.js:4079,4]
```

I'm using react (es6) and I'm importing the transliterate helper via:
`import {transliterate} from 'transliteration/src/main';`

I couldn't get any other method described in the README for the import to work.

Using node v7.4.0 (with npm  v4.1.2)

Is there something I'm missing? Eagerly waiting for you insights ^^

### PR DESCRIPTION
**Pull request by kachkaev**
Adding `babel-preset-es2015` to `.babelrc` makes it possible to use the library in non-configurable webpack environments, such as in [`create-react-app`](https://github.com/facebookincubator/create-react-app).

### CODE REVIEW

**Comment by zenweasel** [comment]
When do you think you would have a chance to pull this in? We had another issues pop up with IE11 (#2535) and Safari (#2546) and this PR seems to fix the problem.

Thanks so much for your work @kachkaev and @andyhu

**Comment by andyhu** [comment]
Apologize for the late reply. I'll do more research with this issue and merge it when it's safe to do so. Would you explain it a bit more on how can I reproduce the issue?

**Comment by zenweasel** [comment]
@andyhu Here's how you would reproduce it using the [Reaction Commerce project](https://github.com/reactioncommerce/reaction). The error currently occurs on our `master` branch but we plan on releasing a new version with the fix in so that may change. It happens in v1.3.0 and v 1.4.0 will have the fix.

1. Install any of [these requirements](https://docs.reactioncommerce.com/reaction-docs/master/requirements) if necessary (probably none except for Meteor)
1.  `npm install -g reaction-cli`
1. `reaction init`
1. `cd reaction`
1. `reaction`
1. View the site in IE11
1. Observe the site never loads and there are console errors.
1. `git checkout development` - observe that the problem is resolved.



It also occurs with Safari if you are using a fully "built" version. We were using the "direct import" method but we also use it on the server side so that caused problems for us.

We created [a fork](https://github.com/reactioncommerce/transliteration) which is just a fork of @kachkaev's repo with the changes in it. Using that fork the problem disappears.

**Comment by thekip** [comment]
this is definitely safe, and should be merged, otherwise you expose ES6 code for environments which don't support it (ie, uglifyJS)

**Comment by core-process** [comment]
Yes, please merge!

**Comment by core-process** [comment]
I published the following package as a workaround: https://www.npmjs.com/package/transliterations

**Comment by VasiliKubarka** [comment]
@andyhu Please, approve this MR! It's blocking my production build

**Comment by aaronjudd** [comment]
Since this never got merged.. @zenweasel should this now be using [babel-preset-env](https://babeljs.io/env/)?

**Comment by core-process** [comment]
@aaronjudd sounds good to me. Will update my clone within the next days.

**Comment by core-process** [comment]
Would love to see some progress on this matter. I see more and more traction to my clone, which is OK, but was not intended initially. @andyhu could you please let us know if you intent to fix this issue? I know we are not paying customers, but a fix would be very simple and it does not hurt. ;-)

**Comment by andyhu** [comment]
@core-process Yes I'll still work on it. I actually tried to merge this PR before but other users reported some strange issues. So I reverted the change. I'm not sure if it's because of the .babelrc in npm root or not. Before I have some time to test it thoroughly on all platforms (Node.js, browser (Bower, Webpack, UMD etc.), React Native, Web Worker and CLI), I'll probably not merge this issue. Anyway I'll try to finish testing by this weekend, along with switching from gulp+browserify to npm script + webpack.

**Comment by ogonkov** [comment]
Isn't it fixed?

**Comment by dzcpy** [comment]
@ogonkov Yes, it's fixed in v2

**Pull request closed without merging**
